apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pipeline
spec:
  params:
    - name: url
      description: Repository URL to clone from.
      type: string
  workspaces:
    - name: source
      description: code source
      mountPath: /workspace/source
  steps:
    - name: clone-repo
      image: alpine/git
      workingDir: $(workspaces.source.path)
      script: |
        git clone $(params.url) $(workspaces.source.path)
        ls
    - name: npm-install
      image: node:14.19
      workingDir: $(workspaces.source.path)
      script: |
        npm config set registry https://mirrors.huaweicloud.com/repository/npm/
        npm install
    - name: npm-build
      image: node:14.19
      workingDir: $(workspaces.source.path)
      script: |
        npm run build
        ls
