apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run
spec:
  pipelineRef:
    name: pipeline
  params:
    - name: url
      value: "https://gitee.com/lomtom/demo-nodejs.git"
  workspaces:
    - name: source
      emptyDir: {}