apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-code
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /data/tekton
    server: 10.168.12.35
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tekton-storage
  volumeMode: Filesystem
status:
  phase: Bound