apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: multi-task-pipeline-run
spec:
  pipelineRef:
    name: multi-task
  params:
    - name: url
      value: "https://github.com/lomtom/demo-nodejs.git"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: tekton-storage
          resources:
            requests:
              storage: 5Gi