apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: docker-task-run
spec:
  taskRef:
    name: docker
  params:
    - name: url
      value: "https://gitee.com/lomtom/demo-nodejs.git"
    - name: dockerfile
      value: "Dockerfile"
    - name: context
      value: "./"
    - name: image
      value: "swr.cn-east-3.myhuaweicloud.com/lomtom-test/lomtom:temp"
  workspaces:
    - name: source
      emptyDir: {}