apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: multi-task-clone
spec:
  params:
    - name: url
      description: Repository URL to clone from.
      type: string
  workspaces:
    - name: source
      description: code source
      mountPath: /workspace/source
  steps:
    - name: clone-repo
      image: alpine/git
      workingDir: $(workspaces.source.path)
      script: |
        CHECKOUT_DIR=$(workspaces.source.path)
        if [[ -d "$CHECKOUT_DIR" ]]; then
          rm -rf "$CHECKOUT_DIR"/*
          rm -rf "$CHECKOUT_DIR"/.[!.]*
          rm -rf "$CHECKOUT_DIR"/..?*
        fi
        git clone $(params.url) $CHECKOUT_DIR
        ls
