apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: multi-task-build
spec:
  workspaces:
    - name: source
      description: code source
      mountPath: /workspace/source
  steps:
    - name: npm-install
      image: node:14.19
      workingDir: $(workspaces.source.path)
      script: |
        npm config set registry https://mirrors.huaweicloud.com/repository/npm/
        npm install
    - name: npm-build
      image: node:14.19
      workingDir: $(workspaces.source.path)
      script: |
        npm run build
        ls
