apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: multi-docker-task
spec:
  params:
    - name: url
      type: string
    - name: dockerfile
      type: string
    - name: context
      type: string
    - name: image
      type: string
  workspaces:
    - name: source
  tasks:
    - name: task-clone
      taskRef:
        name: multi-task-clone
      params:
        - name: url
          value: $(params.url)
      workspaces:
        - name: source
          workspace: source
    - name: task-build
      taskRef:
        name: multi-task-build
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - task-clone
    - name: task-docker
      taskRef:
        name: multi-task-docker
      params:
        - name: dockerfile
          value: $(params.dockerfile)
        - name: context
          value: $(params.context)
        - name: image
          value: $(params.image)
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - task-build